### PR TITLE
Minor README improvement

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Was about to add melpa badge, but realise it isn't available on it so war.

Do you agree I create and publish recipe to melpa? 
https://github.com/milkypostman/melpa/pulls

**Comment by ancane** [comment]
Oh yes, please. Package may not be compliant with melpa yet.
I use this package to check melpa compliance https://github.com/purcell/flycheck-package.

**Comment by AdrieanKhisbe** [comment]
One of purcell remark would be probably to use `markdown-preview--whatever` has prefix rather than `mdpm:whatever`

**Comment by AdrieanKhisbe** [comment]
I added a prefix switch commit in the Pr :smiley:

**Comment by ancane** [comment]
Thanks!

**Comment by AdrieanKhisbe** [comment]
you're welcome. :)

I am the one that should thanks you for your so useful mode !! :smiley:

**Pull request merged**
